[workspace]
members = [
    "utils/immutable_string",
    "dagex_core",
    "dagex_core_algorithms",
    "dagex_phylo",
]
resolver = "2"

[workspace.dependencies]
getrandom = "0.2"
rand = "0.8.5"
ctor = "0.2.8"
smallvec = "1.13.2"
