[workspace]
members = [
    "utils/fnv1a_hasher",
    "utils/immutable_string",
    "dagex",
    "dagex_algorithms",
]
resolver = "2"

[workspace.package]
version = "0.0.2"
edition = "2021"
authors = ["Rafal Szefler <rafael.szefler@gmail.com>"]
rust-version = "1.78"

[workspace.dependencies]
getrandom = "0.2"
rand = "0.8.5"
ctor = "0.2.8"
smallvec = "1.13.2"
fasthash = "0.4"
