[package]
name = "dagex_phylo"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
dagex_core = { path = "../dagex_core" }
immutable_string = { path = "../utils/immutable_string" }
